AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/spring'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'test/test_helper.rb'
    - 'db/seeds.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false